package univr.spesaonline.model;

public enum SceneName {
    START_SCREEN, LOGIN, REGISTER, FULLREGISTER, CATALOG, CART, CARTITEM, OVERVIEWUTENTE, PRODUCTLIST, LOGIN_RESPONSABILE, OVERVIEW_RESPONSABILE;
}
