// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Date;
import model.Ora;
import model.Prodotto;

/************************************************************/
/**
 * 
 */
public class Spesa {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Date dataConsegna;
	/**
	 * 
	 */
	private Ora oraInizio;
	/**
	 * 
	 */
	private Ora oraFine;
	/**
	 * 
	 */
	private int costoTot;
	/**
	 * 
	 */
	private int saldoPunti;
	/**
	 * 
	 */
	private String pagamento;
	/**
	 * 
	 */
	public Prodotto[] prodotto;
	/**
	 * 
	 */
	private String stato;
};
