// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import model.Date;

/************************************************************/
/**
 * 
 */
public class TesseraFedelta {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Date dataEmissione;
	/**
	 * 
	 */
	private int punti;
};
