// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Utente {
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String cognome;
	/**
	 * 
	 */
	private int CAP;
	/**
	 * 
	 */
	private String citta;
	/**
	 * 
	 */
	private int telefono;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private String via;
	/**
	 * 
	 */
	private String nCivico;
	/**
	 * 
	 */
	private String password;
	/**
	 * 
	 */
	private String pagamentoPreferito;
	/**
	 * 
	 */
	private String comune;
};
