// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class ResponsabileReparto {
	/**
	 * 
	 */
	private String matricola;
	/**
	 * 
	 */
	private Date dataNascita;
	/**
	 * 
	 */
	private String via;
	/**
	 * 
	 */
	private String nome;
	/**
	 * 
	 */
	private String città;
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private String cognome;
	/**
	 * 
	 */
	private String nCivico;
	/**
	 * 
	 */
	private String comune;
	/**
	 * 
	 */
	private String comuneDiNascita;
	/**
	 * 
	 */
	private String ruolo;
	/**
	 * 
	 */
	private String password;

	public String getMatricola() {
		return matricola;
	}

	public Date getDataNascita() {
		return dataNascita;
	}

	public String getVia() {
		return via;
	}

	public String getNome() {
		return nome;
	}

	public String getCittà() {
		return città;
	}

	public String getUsername() {
		return username;
	}

	public String getCognome() {
		return cognome;
	}

	public String getnCivico() {
		return nCivico;
	}

	public String getComune() {
		return comune;
	}

	public String getComuneDiNascita() {
		return comuneDiNascita;
	}

	public String getRuolo() {
		return ruolo;
	}

	public String getPassword() {
		return password;
	}

};
